### ISSUE TITLE
Gradle task assembleDebug failed

### ISSUE THREAD

**Issue by ArmanKT** [OjasKarmarkar/Beats#11]
![Screenshot_36](https://user-images.githubusercontent.com/38861462/68404990-8d4dac00-01a9-11ea-9b58-56cfc6e1d267.png)

what is the problem? :/

**Comment by OjasKarmarkar** [comment]
Runs fine here.. did you pull the latest version?

**Comment by kieth1205** [comment]
@OjasKarmarkar I get the same problem with @ArmanKT. I clone this repo and run with visual studio code

**Comment by ArmanKT** [comment]
> Runs fine here.. did you pull the latest version?

yes i pull the latest master file , but it's showing  error  why :/

**Comment by ArmanKT** [comment]
> @OjasKarmarkar I get the same problem with @ArmanKT. I clone this repo and run with visual studio code

gradle problem :/

**Comment by OjasKarmarkar** [comment]
Oh! But day before yesterday i did fix whatever gradle problems were there in the code related to androidX...Can u try downloading the zip file again.. running a flutter clean and flutter pub get before debugging? (Download the Latest One)

**Comment by OjasKarmarkar** [comment]
@kieth1205 I too use vscode! :(

**Comment by OjasKarmarkar** [comment]
https://stackoverflow.com/questions/23330816/error-package-android-support-v7-app-does-not-exist

@ArmanKT @kieth1205 check this.. but i have already merged that thing

**Comment by ArmanKT** [comment]
> Oh! But day before yesterday i did fix whatever gradle problems were there in the code related to androidX...Can u try downloading the zip file again.. running a flutter clean and flutter pub get before debugging? (Download the Latest One)

recently i download latest on but it's show same problem , i think everyone face same problem 

thank you 0_o

**Comment by OjasKarmarkar** [comment]
Okay..let me see again... If we come up with a fix I'll share it :).. Also check the play store one by tomorrow or something.. updated the code today

**Comment by OjasKarmarkar** [comment]
Leaving this issue open until it's solved

**Comment by nullhandler** [comment]
@ArmanKT @kieth1205 we migrated the flute-music-player library to androidx. We made a pull request to @iampawan , but still its not updated in the pub.dev. So, download [this folder](https://drive.google.com/folderview?id=1kGLGpYK_0Ta74yFqXOcMkU5uHvJyia51) and replace the one in your `C:/flutter/.pub-cache/pub.dartlang.org/flute_music_player-0.0.6/` folder. Then, try to run it.

**Comment by ismailceliktr** [comment]
Thanks for the update. Also notice that, after download @selvasoft 's folder, don't forget to change android/local.properties file. You should set your SDK directory like this `sdk.dir=C:\\Users\\<Your-Username>\\AppData\\Local\\Android\\sdk` or something like this.

**Comment by nullhandler** [comment]
@ismailceliktr thanks. Didnt noticed it.
