### ISSUE TITLE
import android.support.v7.app.AppCompatActivity

### ISSUE THREAD

**Issue by johanguse** [OjasKarmarkar/Beats#9]
I like to see this beautiful app, but I think there's a error on flute_music_player

https://github.com/iampawan/Flute-Music-Player/issues/16

C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flute_music_player-0.0.6\android\src\main\java\com\mtechviral\musicfinder\MusicHelper.java:10: error: 
package android.support.v7.app does not exist
import android.support.v7.app.AppCompatActivity;
                             ^
C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flute_music_player-0.0.6\android\src\main\java\com\mtechviral\musicfinder\MusicHelper.java:15: error: 
cannot find symbol
    public static boolean hasExternalStorageAccess(AppCompatActivity activity) {
                                                   ^
  symbol:   class AppCompatActivity
  location: class MusicHelper
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flute_music_player-0.0.6\android\src\main\java\com\mtechviral\musicfinder\MusicFinderPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\flute_music_player-0.0.6\android\src\main\java\com\mtechviral\musicfinder\MusicFinderPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
Running Gradle task 'assembleDebug'...
Running Gradle task 'assembleDebug'... Done                        24.6s
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1

**Comment by OjasKarmarkar** [comment]
you can check the playstore to try the app!..Also I'll migrate it to androidX asap!
here : https://play.google.com/store/apps/details?id=in.selvasoft.beats

**Comment by OjasKarmarkar** [comment]
@johanguse
 Updated! Please Check Now!

**Comment by DIMITA** [comment]
How can i resolve this problem in my app
 error: package android.support.v7.app does not exist
